# auth-global hooks will be managed / updated across all auth repos.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Lint trailing whitespace
        exclude_types: [image]
      - id: end-of-file-fixer
        name: Lint end-of-file newline
        exclude_types: [image]
      - id: check-added-large-files
        name: Don't permit large files
        exclude_types: [image]

  - repo: local
    hooks:
      - id: go-mod-tidy
        name: Go mod tidy
        language: system
        entry: go mod tidy
        types: [go]
        pass_filenames: false
      - id: golangci-lint
        name: Go linting
        language: system
        entry: golangci-lint run --fix --timeout=5m
        pass_filenames: false
        types: [go]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: JSON and YAML formatting
        types_or: [json, yaml]
