// Code generated by "stringer -output function_string.go -linecomment -trimprefix Func -type FuncType,LogicalType"; DO NOT EDIT.

package spec

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FuncLiteral-1]
	_ = x[FuncSingularQuery-2]
	_ = x[FuncValue-3]
	_ = x[FuncNodes-4]
	_ = x[FuncLogical-5]
}

const _FuncType_name = "LiteralSingularQueryValueNodesLogical"

var _FuncType_index = [...]uint8{0, 7, 20, 25, 30, 37}

func (i FuncType) String() string {
	i -= 1
	if i >= FuncType(len(_FuncType_index)-1) {
		return "FuncType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _FuncType_name[_FuncType_index[i]:_FuncType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LogicalFalse-0]
	_ = x[LogicalTrue-1]
}

const _LogicalType_name = "falsetrue"

var _LogicalType_index = [...]uint8{0, 5, 9}

func (i LogicalType) String() string {
	if i >= LogicalType(len(_LogicalType_index)-1) {
		return "LogicalType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogicalType_name[_LogicalType_index[i]:_LogicalType_index[i+1]]
}
